spring.application.name=todo-manager
server.error.include-stacktrace=always
server.error.include-message=always

#jdbc
spring.datasource.url=jdbc:mysql://localhost:3306/springtutorial
spring.datasource.username=root
spring.datasource.password=root